# Generated by Django 2.1.6 on 2019-03-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=30)),
                ('city_zip_code', models.CharField(max_length=10)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=50)),
                ('person_birthDate', models.DateField()),
            ],
        ),
    ]
