# Generated by Django 2.1.6 on 2019-03-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city_zip_code',
        ),
        migrations.AddField(
            model_name='city',
            name='city_zip_code',
            field=models.CharField(default='0000', max_length=10),
            preserve_default=False,
        ),
    ]
